### PR TITLE
add non-polyfilled entrypoint typings

### PR DESCRIPTION
**Pull request by mad-gooze**
That's an addition for two my previous requests https://github.com/creeperyang/id3-parser/pull/14 and https://github.com/creeperyang/id3-parser/pull/15: it adds a possibility to use non-polyfilled entrypoint from typescript and test for typescript typings validity.

It also adds a `package-lock.json` file (see https://docs.npmjs.com/files/package-lock.json).

### CODE REVIEW

**Comment by mad-gooze** [comment]
release please?

**Comment by creeperyang** [comment]
@mad-gooze `v1.5.0` released.

**Comment by mad-gooze** [comment]
@creeperyang something is wrong - there is no `id3Parser.d.ts` file in the npm package, so typings are broken if you install from npm.
```
bash-3.2$ npm pack id3-parser
id3-parser-1.5.0.tgz
bash-3.2$ tar zxvf id3-parser-1.5.0.tgz
x package/package.json
x package/README.md
x package/dest/id3-parser.browser.js
x package/dest/id3-parser.browser.min.js
x package/dest/id3-parser.browser.min.js.map
x package/index.d.ts
x package/lib/frameTypes.js
x package/lib/genres.js
x package/lib/global.js
x package/lib/imageTypes.js
x package/lib/parser-non-polyfilled.js
x package/lib/parser.js
x package/lib/stringUtils.js
x package/lib/parser-non-polyfilled.d.ts
bash-3.2$ tree
.
├── id3-parser-1.5.0.tgz
└── package
    ├── README.md
    ├── dest
    │   ├── id3-parser.browser.js
    │   ├── id3-parser.browser.min.js
    │   └── id3-parser.browser.min.js.map
    ├── index.d.ts
    ├── lib
    │   ├── frameTypes.js
    │   ├── genres.js
    │   ├── global.js
    │   ├── imageTypes.js
    │   ├── parser-non-polyfilled.d.ts
    │   ├── parser-non-polyfilled.js
    │   ├── parser.js
    │   └── stringUtils.js
    └── package.json

3 directories, 15 files
```

**Comment by creeperyang** [comment]
@mad-gooze `v1.5.1` released to fix the error.

**Pull request merged**
